### ISSUE TITLE
Single responsibility?

### ISSUE THREAD

**Issue by drongood12** [timmybo5/simple-weapon-base#103]
I'll just leave this here, it hurts me too much to look at.

https://en.wikipedia.org/wiki/Single-responsibility_principle
https://stackoverflow.com/questions/2477839/are-cs-partial-classes-bad-design

**Comment by timmybo5** [comment]
It's a design habit I picked up from the Facepunch devs, what I like about it is that I don't have to instantiate a bunch of classes with methods and properties that ideally should be available directly on the main class but instead of bloating the main file I can split it up. Specially now that we have components (which is the only way to get networking) I don't like having to instantiate a ton of components.

I can see why not everyone would agree with this style of code separation. You are always welcome to make a pr that doesn't use using partial classes and we can take it from there :)
